on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to github pages
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with: 
            node-version: '21.x'
        - run: sudo apt-get install sshpass
        - run: echo alias gitpass='sshpass -v -P "Enter passphrase for key" -p $SSH_PASSWORD' >> ~/.bashrc
        - run: npm ci
        - run: npm run build 
        - run: cd dist
        - run: mkdir remote_dist && cd remote_dist
        - run: echo $0
        - run: gitpass git clone git@github.com:mutawwir-blog/mutawwir-blog.github.io
        - run: rm -rf ./*
        - name: Copy contents of parent dist into child remote dist, without copying in child dist too
          run: find ../ -maxdepth 1 -printf "%f\n" | grep -v -E "(^remote_dist$|^\.\./$)" | while read sibling; do cp ../$sibling ./; done
        - run: git add .
        - run: git commit -m "local update"
        - run: gitpass git push
      
    
